import assert from 'node:assert/strict';
import path from 'node:path';

export async function navigationChecks(page,{touch,label,output}) {
  const tap=async selector=>{const node=page.locator(selector);if(touch)await node.tap();else await node.click();};
  const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('tonedef.current.v2')));
  // Isolated browser-test fixture; never replace music in a real user session.
  await page.evaluate(async()=>{
    const {example}=await import('./src/model.js');
    localStorage.setItem('tonedef.current.v2',JSON.stringify(example('progression')));
    localStorage.setItem('tonedef.workspace.mode.v3','learn');
  });
  await page.reload();await page.waitForSelector('#quick-instrument');
  const original=await saved();
  const setupTarget=await page.locator('#quick-instrument').boundingBox();
  assert.ok(setupTarget.width>=44&&setupTarget.height>=44,'The direct setup control is a full-size touch target');
  await tap('#simple-menu > summary');
  await tap('#learn-topic-intervals');
  assert.equal(await page.locator('#simple-menu').evaluate(n=>n.open),false,'More dismisses when another action is chosen');
  await tap('#simple-menu > summary');await page.keyboard.press('Escape');
  assert.equal(await page.locator('#simple-menu').evaluate(n=>n.open),false);
  assert.equal(await page.evaluate(()=>document.activeElement.parentElement.id),'simple-menu','Escape restores menu focus');
  await tap('#learning-info > summary');
  await tap('#workspace-practice');
  await tap('#practice-shape > summary');await tap('#practice-more > summary');
  assert.equal(await page.locator('#practice-reach').evaluate(n=>n.parentElement.id),'practice-shape','Reach is not nested inside rhythm');
  assert.equal(await page.locator('#practice-ranges').evaluate(n=>n.parentElement.id),'practice-shape','Fret ranges have a direct disclosure');
  const stacked=await page.evaluate(()=>matchMedia('(max-width:1099px), (max-height:699px)').matches);
  if(!stacked) {
    const neck=await page.locator('#simple-fretboard').boundingBox(),guide=await page.locator('#step-guide').boundingBox();
    const pattern=await page.locator('#simple-timeline').boundingBox(),keep=await page.locator('[data-action="lock-event"]').boundingBox();
    assert.ok(guide.y+guide.height<=neck.y+neck.height,'The complete step guide fits beside the configuration choices');
    assert.ok(keep.y+keep.height<=pattern.y+pattern.height,'The pattern action remains fully visible');
  }
  if(!stacked)await page.locator('#simple-exercise').evaluate(n=>{n.scrollTop=150;});
  const choicesScroll=await page.locator('#simple-exercise').evaluate(n=>n.scrollTop);
  await tap('#quick-instrument');
  assert.equal(await page.locator('#workspace-practice').getAttribute('aria-pressed'),'true','Setup stays in the current workspace');
  assert.equal(await page.locator('#config-tab-instrument').getAttribute('aria-selected'),'true');
  assert.equal(await page.locator('#setting-stringCount').isVisible(),true);
  assert.equal(await page.locator('#recall').count(),0,'Setup has no unrelated challenge controls');
  assert.deepEqual(await saved(),original,'Opening setup does not save or change music');
  await page.locator('#config-tab-instrument').focus();await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#config-tab-sound').getAttribute('aria-selected'),'true');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'config-tab-sound');
  await page.locator('#setting-volume').fill('30');await page.locator('#setting-volume').press('Tab');
  assert.equal((await saved()).settings.volume,30);
  assert.deepEqual((await saved()).events,original.events,'Sound configuration leaves all music intact');
  assert.equal(await page.locator('#config-tab-sound').getAttribute('aria-selected'),'true','Editing keeps its section');
  assert.equal(await page.locator('#setting-volume').inputValue(),'30');
  await page.locator('[data-value-for="setting-volume"]').focus();await page.keyboard.press('ArrowRight');
  assert.equal((await saved()).settings.volume,35,'Volume slider and exact entry share one transaction path');
  await tap('[data-action="undo"]');assert.equal((await saved()).settings.volume,30);
  await tap('[data-action="undo"]');
  assert.deepEqual(await saved(),original,'Undo exactly restores setup and music');
  assert.equal(await page.locator('#config-tab-sound').getAttribute('aria-selected'),'true');
  await tap('#config-tab-display');
  assert.equal(await page.locator('#setting-labels').isVisible(),true);
  assert.equal(await page.locator('#setting-volume').isVisible(),false);
  assert.equal(await page.locator('[role="tab"][tabindex="0"]').count(),1);
  await page.keyboard.press('Home');
  assert.equal(await page.locator('#config-tab-instrument').getAttribute('aria-selected'),'true');
  await page.locator('#instrument-preset').focus();await page.locator('#instrument-preset').selectOption('Bass · 4 strings');
  await page.locator('#modal[open]').waitFor();
  assert.deepEqual(await saved(),original,'Retuning asks how to preserve notes before committing');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#modal').evaluate(n=>n.open),false);
  assert.equal(await page.locator('#instrument-preset').inputValue(),'Guitar · standard');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'instrument-preset','Cancelling retune returns to its control');
  assert.deepEqual(await saved(),original);
  await page.locator('#instrument-preset').selectOption('Guitar · Drop D');
  await page.locator('#modal[open]').waitFor();await tap('[data-policy="positions"]');
  assert.equal((await saved()).settings.open0,38,'Confirmed tuning applies through existing reconciliation');
  assert.equal(await page.locator('#config-tab-instrument').getAttribute('aria-selected'),'true');
  assert.equal(await page.evaluate(()=>document.activeElement.id),'instrument-preset');
  await tap('[data-action="undo"]');assert.deepEqual(await saved(),original);
  await page.locator('#setting-stringCount').fill('13');await page.locator('#setting-stringCount').press('Tab');
  assert.equal(await page.locator('#setting-stringCount').inputValue(),'6','Invalid input restores the actual value');
  assert.deepEqual(await saved(),original);
  await page.screenshot({path:path.join(output,`${label}-instrument-setup.png`),fullPage:true});
  await tap('#simple-menu > summary');await page.keyboard.press('Escape');
  assert.equal(await page.locator('.configuration-panel').isVisible(),true,'Escape closes the menu before setup');
  await tap('#config-back');
  for(const id of ['practice-shape','practice-more'])assert.equal(await page.locator('#'+id).evaluate(n=>n.open),true,'Back restores open practice choices');
  if(!stacked)assert.ok(Math.abs(await page.locator('#simple-exercise').evaluate(n=>n.scrollTop)-choicesScroll)<2,'Back restores the sidebar scroll position');
  await tap('#workspace-learn');
  assert.equal(await page.locator('#learn-topic-intervals').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#learning-info').evaluate(n=>n.open),true,'Learn keeps its own disclosures');
  await tap('#workspace-practice');
  assert.equal(await page.locator('#practice-more').evaluate(n=>n.open),true,'Views remember their own configuration position');
  await tap('#quick-instrument');await tap('#quick-instrument');
  assert.equal(await page.locator('.configuration-panel').count(),0,'The Instrument shortcut toggles setup closed');
  assert.deepEqual(await saved(),original,'All navigation leaves project bytes unchanged');
  if(stacked) {
    assert.equal(await page.locator('.workspace-jumps').isVisible(),true);
    for(const id of ['fretboard','timeline','exercise']) {
      await tap('#jump-'+id);
      await page.waitForFunction(id=>document.querySelector('#jump-'+id)?.getAttribute('aria-current')==='true',id);
      assert.equal(await page.evaluate(()=>document.activeElement.id),'simple-'+id,'Section jumps move keyboard focus with the view');
      const rect=await page.locator('.workspace-jumps').boundingBox();
      assert.ok(rect.y>=0&&rect.y+rect.height<=page.viewportSize().height+1,'Section navigation remains reachable');
    }
    await tap('#jump-fretboard');await tap('#quick-instrument');
    assert.equal(await page.locator('#jump-exercise').innerText(),'Setup');
    const top=await page.locator('#simple-exercise').boundingBox(),header=await page.locator('.topbar').boundingBox();
    assert.ok(top.y>=header.height-1&&top.y<header.height+25,'Setup opens below the sticky header');
    await page.keyboard.press('Escape');
  } else assert.equal(await page.locator('.workspace-jumps').isVisible(),false);
  const duplicateIds=await page.locator('[id]').evaluateAll(nodes=>nodes.map(n=>n.id).filter((id,i,all)=>all.indexOf(id)!==i));
  assert.deepEqual(duplicateIds,[]);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.deepEqual(await saved(),original);
  await page.screenshot({path:path.join(output,`${label}-navigation.png`),fullPage:true});
  return ['in-place setup with keyboard tabs','exact sound Undo','retune cancellation and focus recovery','confirmed instrument reconciliation and Undo','invalid-setting recovery','independent view disclosure/scroll memory','outside/Escape menu dismissal','flattened practice sections','responsive section navigation and focus','unchanged saved project'];
}
